name: date-in
version: '0.1.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=postgresql://postgres:postgres@db:5432/clone?schema=public
    container_name: nextjs_app
    environment:
      - DATABASE_URL=DATABASE_URL=postgresql://postgres:postgres@db:5432/clone?schema=public
      - NEXT_WEBPACK_USEPOLLING=1
    ports: 
      - '3000:3000'
      - '5555:5555'
    volumes:
      - /app/.next
      - /app/node_moduls
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: postgres:apline
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clone
    ports:
      - 5432:5432
    volumes:
      - postres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}' ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: