import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import QuaryClient from "@/quary/QuaryClient";
import BottomBar from "@/components/bottomBar";
import { Poppins } from "next/font/google";

const inter = Poppins({ subsets: ["latin"], weight: ["400", "500", "600", "700", "800", "900"] });


export const metadata: Metadata = {
  title: "Date-in",
  description: "Generated by Date-in",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}   >
        <QuaryClient>
          <Toaster />
          <div className=" relative w-full min-h-screen ">
            {children}
          </div>
        </QuaryClient>
      </body>
    </html>
  );
}
